### ISSUE TITLE
Add details page subtitles

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalWebsite#14]
Please add subtitles to the details page as shown below for all donation scenarios (one-time, subscription, donate page, campaign page) . . . 

- Your name as you'd like it to appear in our records (required)
- The address at which you'd like to receive Renewal communications (optional, not related with card verification)
- Your card information

![screenshot 96 _li](https://user-images.githubusercontent.com/13606352/43983211-ef08c724-9d2b-11e8-9087-ba52f3f0bc6f.jpg)

**Comment by kolte** [comment]
this is fixed, please review

**Comment by d33pspace** [comment]
@elainetao829 I believe you opened one or more issues related with this. Can you take a look at this and consolidate your issue(s) here if possible?

**Comment by elainetao829** [comment]
Your Card Information is smaller than Expiry Date, which is strange.

![image](https://user-images.githubusercontent.com/42002784/44305436-a81be100-a3a9-11e8-8b7f-c0f14aa10bf4.png)

**Comment by elainetao829** [comment]
Dear @kolte 
As Jimmy referenced, now there are two problems need to be fixed,

1. Your card information --> the font of this sentence is smaller than Expiration Date, which is strange. I think this should larger. @d33pspace please confirm here.

2. Issue #33 , please find the details in the issue. Thanks.

**Comment by kolte** [comment]
@d33pspace @elainetao829 this is fixed, please review

**Comment by d33pspace** [comment]
(1) Add "s" to "record" making "records".
(2) Add spaces after "communications" and "optional" making "...Renewal communications (optional, not related..."
(3) Move "The address at which you'd like to receive Renewal communications (optional, not related with card verification)" down below the Name field but above the address fields. 
(4) Increase the font size of the three subtitles (indicated in blue in the screenshot below), they should be larger than "Expiration Date" and "Security Code" but smaller than "Please enter your details below:"

![screenshot 163 _li](https://user-images.githubusercontent.com/13606352/44505371-a452cc00-a6d3-11e8-92b3-ffa83e225cc5.jpg)

**Comment by elainetao829** [comment]
Verified and it's not fixed.

1. I think this page has been translated to Chinese before. But now it's mixing Chinese and English together again. Can you please get the translation back?

![image](https://user-images.githubusercontent.com/42002784/44531281-fcfd8580-a722-11e8-8321-caee182d7278.png)
In case you can't find the old translation, please use this one below.
The address at which you'd like to receive Renewal communications ( optional, not related with card verification) --> 您希望与日新中心联络的通讯地址（可选，与卡片验证无关）。

2. When there is card information stored before, the message about address information is not placed at the right position.

![image](https://user-images.githubusercontent.com/42002784/44531534-9a58b980-a723-11e8-85f3-11d2b0585ee9.png)

**Comment by d33pspace** [comment]
Hi @kolte this seems mostly fixed, but please see the screenshot below, this is one of the RePayment views which hasn't been properly updated yet. This is one of the reasons I don't like all the code duplication here.

![inkedscreenshot 174 _li](https://user-images.githubusercontent.com/13606352/44616602-2e8e6200-a885-11e8-8e71-d6577537957c.jpg)

**Comment by elainetao829** [comment]
@kolte please see the comment from Jimmy above.

**Comment by d33pspace** [comment]
@kolte I'm going a little crazy here. Please see the screenshot below, in this case the subtitle has been moved down too far. Can you please carefully work this out and make sure all four views are the same please? :)

![screenshot 177 _li](https://user-images.githubusercontent.com/13606352/44784338-e2faf180-abbf-11e8-99e5-ab2c4c9ebbfe.jpg)

**Comment by elainetao829** [comment]
Tested 4 scenarios and confirm fixed.
