### ISSUE TITLE
PDF generation should not be allowed for blank reports

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalWebsite#25]
If the Invoice History search (including default) does not return any results, please disable the PDF button so users can't generate blank reports.

**Comment by kolte** [comment]
this is fixed, please review

**Comment by d33pspace** [comment]
@elainetao829 Please give this a look when you can.

**Comment by elainetao829** [comment]
Verified and the problem is not completely solved. 
When user opens the history tab, she/he is still able to click the PDF button before the automatic search is done. Therefore, the user will still get an empty PDF.
I would suggest we do not display this PDF button by default unless the system searches out some results.

![image](https://user-images.githubusercontent.com/42002784/44345660-8401f200-a4c6-11e8-942a-c063d6f56820.png)

**Comment by d33pspace** [comment]
@kolte Please take a look at this. I don't have a preference whether or not the PDF button is disabled or not visible, but users should not be able to generate empty PDFs. Thanks.

**Comment by elainetao829** [comment]
The layout has been changed completely. This ticket is out of date.
